name: Tag on Version Change

on:
  push:
    branches:
      - master

jobs:
  tag_version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for version changes
      id: check_version
      run: |
        # Get the previous version from the last release tag
        export previous_version=$(git describe --tags --abbrev=0)
        
        # Get the current version from pubspec.yaml
        export current_version=$(cat pubspec.yaml | grep 'version:' | awk '{print $2}')
        
        if [[ "$previous_version" != "$current_version" ]]; then
          echo "Version has changed from $previous_version to $current_version."
          echo "::set-output name=version_changed::true"
        else
          echo "Version has not changed."
          echo "::set-output name=version_changed::false"
        fi

    - name: Push Git Tag
      if: steps.check_version.outputs.version_changed == 'true'
      run: |
        # Push a Git tag with the new version
        export current_version=$(cat pubspec.yaml | grep 'version:' | awk '{print $2}')
        git tag -a "v$current_version" -m "Version $current_version"
        git push origin "v$current_version"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
