name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit messages and changes
        id: commit_changes
        run: |
          TAG_NAME="${{ github.ref }}"
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          COMMIT_MESSAGES=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..$TAG_NAME)
          DIFF=$(git diff $PREVIOUS_TAG..$TAG_NAME)
          echo "Changes in this Release"
          echo "$COMMIT_MESSAGES"
          echo "Code changes:"
          echo "$DIFF"
          echo "::set-output name=commit_messages::Changes in this Release\n$COMMIT_MESSAGES\n\nCode changes:\n$DIFF"
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.commit_changes.outputs.commit_messages }}
          draft: false
          prerelease: false