name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get previous tag
        id: previous_tag
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ github.ref }}^)
          echo "::set-output name=previous_tag::$PREVIOUS_TAG"
        shell: bash

      - name: Get commit messages and changes
        id: commit_changes
        run: |
          PREVIOUS_TAG=${{ steps.previous_tag.outputs.previous_tag }}
          COMMIT_MESSAGES=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..${{ github.ref }})
          COMPARE_URL="https://github.com/${{ github.repository }}/compare/${{ steps.previous_tag.outputs.previous_tag }}...${{ github.ref }}"
          echo "::set-output name=commit_messages::$COMMIT_MESSAGES\n\n[View changes]($COMPARE_URL)"
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.commit_changes.outputs.commit_messages }}
          draft: false
          prerelease: false